# crie a imagem com:
# docker build -f Dockerfile.multistage -t agenda .
#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:16-alpine3.13
COPY --from=build /home/app/target/agenda-0.0.1-SNAPSHOT.jar /usr/local/lib/agenda.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/agenda.jar"]